development:
    type: imap
    server: mail-gw.frgcms.com 
    username: admin@frgcms.com
    password: laurenrothlisberger
    receiver: MessageMailer
    port: 2500 

test:
    type: imap
    server: imap.gmail.com
    username: frgcms@gmail.com
    password: frg1cms1
    
production:
    type: imap
    server: mail.blueboxgrid.com  
    username: admin@frgcms.com
    password: laurenrothlisberger
    receiver: MessageMailer
    port: 2500
