development:
    type: imap
    server: imap.gmail.com
    username: frgcms@gmail.com
    password: frg1cms1
    receiver: MessageMailer
    ssl: true
    port: 993

test:
    type: imap
    server: imap.gmail.com
    username: frgcms@gmail.com
    password: frg1cms1
    
production:
    type: imap
    server: imap.gmail.com
    username: frgcms@gmail.com
    password: frg1cms1