#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment.rb'

class MailFetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{RAILS_ROOT}/config/mail.yml")
  
  @config = @config[RAILS_ENV].to_options
  
  @sleep_time = @config.delete(:sleep_time) || 60
  
  #START:start
  def self.start
    puts "Starting MailFetcherDaemon"
    @fetcher = Fetcher.create({:type => :imap,
                                 :receiver => MessageMailer,
                                 :server => 'imap.gmail.com',
                                 :username => 'frgcms@gmail.com',
                                 :password => 'frg1cms1',
                                 :ssl => 'true',
                                 :port => 993,
                                 :use_login => true})
    

    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end
  end
  #END:start
  
  def self.stop
    puts "Stopping MailFetcherDaemon"
  end
  
end

MailFetcherDaemon.daemonize
